// Shoot Them Up Game, All Rights Reserved

#include "Components/STUHealthComponent.h"
#include "GameFramework/Actor.h"
#include "TimerManager.h"

DEFINE_LOG_CATEGORY_STATIC(LogHealthComponent, All, All)

// Sets default values for this component's properties
USTUHealthComponent::USTUHealthComponent()
{
    // Set this component to be initialized when the game starts, and to be ticked every frame.  You can turn these features
    // off to improve performance if you don't need them.
    PrimaryComponentTick.bCanEverTick = false;

    // ...
}

// Called when the game starts
void USTUHealthComponent::BeginPlay()
{
    Super::BeginPlay();

    Health = MaxHealth;
    OnHealthChanged.Broadcast(Health);

    AActor* ComponentOwner = GetOwner();
    if (ComponentOwner)
    {
        ComponentOwner->OnTakeAnyDamage.AddDynamic(this, &USTUHealthComponent::OnTakeAnyDamage);
    }
}

void USTUHealthComponent::OnTakeAnyDamage(
    AActor* DamagedActor, float Damage, const class UDamageType* DamageType, class AController* InstigatedBy, AActor* DamageCauser)
{
    if (Damage <= 0.0f || IsDead()) return;
    Health = FMath::Clamp(Health - Damage, 0.0f, MaxHealth);
    OnHealthChanged.Broadcast(Health);
    if (IsDead())
    {
        OnDeath.Broadcast();
    }
    else
    {
        if (GetWorld() && isAutoHeal() && Health < MaxHealth)
        {
            GetWorld()->GetTimerManager().ClearTimer(TimerHandle);
            GetWorld()->GetTimerManager().SetTimer(TimerHandle, this, &USTUHealthComponent::TakeHeal, HealDelay, false);
        }
    }
}

void USTUHealthComponent::TakeHeal()
{
    if (Health == MaxHealth || IsDead() || !GetWorld()) return;
    Health = FMath::Clamp(Health + HealModifier, 0.0f, MaxHealth);
    OnHealthChanged.Broadcast(Health);
    GetWorld()->GetTimerManager().SetTimer(TimerHandle, this, &USTUHealthComponent::TakeHeal, HealUpdateTime, false);
}
